# PostgreSQL. Versions 9.3 and up are supported.

default: &default
  adapter: postgresql
  encoding: unicode
  # For details on connection pooling, see Rails configuration guide
  # https://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: mondak_test_development

test:
  <<: *default
  database: mondak_test_test

production:
  <<: *default
  database: mondak_test_production
  username: mondak_test
  password: <%= ENV["MONDAK_TEST_DATABASE_PASSWORD"] %>
